# Generated by Django 2.2.16 on 2022-05-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220511_1302'),
        ('reviews', '0005_auto_20220511_1503'),
    ]

    operations = [
    ]
